version: '3.8'
services:
  excalidraw:
    image: excalidraw/excalidraw
    container_name: excalidraw
    ports:
      - '3000:80'
    restart: on-failure
    stdin_open: true
    healthcheck:
      disable: true
